import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
import Navbar from '@/app/components/Navbar';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nexus',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <body className="min-h-screen">
            <Navbar />
            <div className="container max-w-7x1 mx-auto h-full pt-12">{children}</div>
          </body>
        </Providers>
      </ClerkProvider>
    </html>
  );
}
